### ISSUE TITLE
Yocto.Contrib

### ISSUE THREAD

**Issue by Mrsevic** [Silvenga/Yocto.Contrib#1]
When I build the project for x64 platform I recieve an error saying yapi module not found. No issues whatsoever whilst building for x86 platform. Any hint on where the problem is? 

Will post the exact error later on.

Thanks

**Comment by Silvenga** [comment]
Whoa, I need to update this thing to target the new stuff - time flies. I'll see if I have time this weekend - going to be a little busy. 😿 

Yeah, any extra details would be helpful.

**Comment by Silvenga** [comment]
Try now, I publish 2.0.0 - targeting .Net Standard 2.0. I was able to remove some of my hacks with the upgrade.

**Comment by Mrsevic** [comment]
Thank you very much. I will try it as soon as possible and return with the feedback.

**Comment by Mrsevic** [comment]
Thanks, it is working now.
